Solution
mate-academy/py-taxi-service-user-form-and-validation pull request #313
Opened 2023-07-24 15:46 UTC by oleksandr-lysanets

![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/120311584/a3eb52fa-ee92-4b49-b259-92c104632d35)
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/120311584/9f8e66fb-920d-42a7-8b15-18a039d13fee)
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/120311584/4d40462e-7dda-46b3-9702-14e8dca73714)
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/120311584/24cd7eff-953f-4d7b-a0f4-4d9c02f0b803)
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/120311584/d548e907-f755-4b8c-a1cf-c72c2be3e860)
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/120311584/3d38617f-41e2-49ff-a676-9481230d91df)
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/120311584/5cc62c57-080d-4ac4-b10e-d5983e237d58)
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/120311584/3f2005ee-2cb5-46ab-a46f-ac25aeb52d9a)
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/120311584/617abfbe-3891-4b36-a017-cee3010d6277)

2023-07-24 18:59 UTC, oleksandr-lysanets commented
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/120311584/a568c732-733e-45e4-a96a-8b550fbc8fd2)

2023-07-25 07:43 UTC, olena-hul requested changes

2023-07-25 07:43 UTC, olena-hul commented on taxi/views.py
> +def add_or_delete_driver(request, pk):
Rewrite to class-based view

2023-07-25 07:43 UTC, olena-hul commented on templates/taxi/driver_confirm_delete.html
> +{% endblock %}
Add empty lines to the templates where missing

2023-07-27 07:17 UTC, olena-hul requested changes

2023-07-27 07:17 UTC, olena-hul commented on taxi/urls.py
> +        DriverDeleteView.as_view(),
You should not reuse DriverDeleteView here

2023-07-27 07:17 UTC, olena-hul commented on taxi/urls.py
> +        "drivers/<int:pk>/add_delete",
Add `/` to the end of the url

2023-07-27 07:37 UTC, olena-hul requested changes

2023-07-27 07:37 UTC, olena-hul commented on taxi/urls.py
> +    ),
Add or delete view should still be present, but you should use separate class-based AddDeleteDriverView, not just DeleteDriverView

2023-07-28 07:47 UTC, olena-hul approved these changes

2023-07-28 07:48 UTC, olena-hul commented
Good job!

2024-03-07 17:09 UTC, closed without merging