created user form and validation
mate-academy/py-taxi-service-user-form-and-validation pull request #644
Opened 2024-07-06 18:03 UTC by Timur5050

2024-07-06 18:04 UTC, Timur5050 commented
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/79165970/f3cca1d9-e138-483f-a84d-11f407f9a69d)
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/79165970/602704d4-bedc-4f26-aaf9-4d436181e609)
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/79165970/c68210c5-4561-4096-b246-3fa5645ceba4)
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/79165970/d59b8528-32e9-47c9-aea9-609a5cbdc2fe)
![image](https://github.com/mate-academy/py-taxi-service-user-form-and-validation/assets/79165970/bc811089-1c9d-4143-a0ac-6374e48f2fee)

2024-07-07 09:35 UTC, viktoria-rybenchuk requested changes

2024-07-07 09:35 UTC, viktoria-rybenchuk commented on taxi/forms.py
> +from .models import Driver, Car
use absolute imports

2024-07-07 09:35 UTC, viktoria-rybenchuk commented on taxi/views.py
> +from .forms import DriverCreateForm, DriverLicenseUpdateForm, CarCreateForm
the same here

2024-07-07 09:35 UTC, viktoria-rybenchuk commented on taxi/views.py
> +    return HttpResponseRedirect(car.get_absolute_url())
write this logic with one function if the driver in car.drivers then remove this user from the car, otherwise add

2024-07-07 09:35 UTC, viktoria-rybenchuk commented on templates/taxi/driver_confirm_delete.html
> +    <input type="submit" value="Yes" class="btn btn-danger">
add `Cancel` button, read the checklist

2024-07-07 09:35 UTC, viktoria-rybenchuk commented on templates/taxi/driver_form.html
> +{% endblock %}
add a blank line in the end of the file

2024-07-07 13:55 UTC, Dimosphen1 requested changes
Several changes were requested

2024-07-07 13:55 UTC, Dimosphen1 commented on taxi/urls.py
> +        "delete/or/add/<int:driver_id>/driver/from/<int:car_id>/car/",
Rewrite paths to follow REST conventions

2024-07-07 14:34 UTC, pavlopro approved these changes
Good Job!

2024-08-06 15:13 UTC, closed without merging